version: 0.18.{build}
image: Visual Studio 2019
configuration: Release
before_build:
- cmd: nuget restore source\Loom.sln
build:
  verbosity: minimal
  project: source\Loom.sln
after_build:
test: off
artifacts:
- path: '**\Loom**.nupkg'
- path: '**\Loom**.snupkg'
deploy:
- provider: NuGet
  server:
  api_key:
    secure: rFmF+VnR00KXB0hBWgJnV2TfoyhCABlABiWUPsWfe077lPrWXV4Wh7H/KB6piRf3
  skip_symbols: false
  symbol_server:
